from typing import TypedDict, Optional, Dict
from datetime import datetime

class Contact(TypedDict):
    """Type definition for contact information stored in JSONB"""
    email: Optional[str]
    phone_number: Optional[str]
    notes: Optional[str]

class Conversation(TypedDict):
    """Type definition for conversation records"""
    id: str  # UUID generated by Supabase
    room_url: str
    created_at: datetime
    updated_at: Optional[datetime]
    contact: Optional[Contact]  # JSONB column for contact information
    status: str  # 'active' or 'ended'
    transcript: Optional[Dict]  # JSONB column storing conversation transcript
